// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0EyTlAF2oig3EjIgubHNyEVRQTeH4L5k',
    appId: '1:49185547481:android:bafc9276b96fa77af60ac8',
    messagingSenderId: '49185547481',
    projectId: 'gen-lang-client-0115699822',
    storageBucket: 'gen-lang-client-0115699822.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy4UXRyOiR9fg90AoUKeIHDEFHSEGLADw',
    appId: '1:49185547481:web:c5bbccfe9f7c66a9f60ac8',
    messagingSenderId: '49185547481',
    projectId: 'gen-lang-client-0115699822',
    authDomain: 'gen-lang-client-0115699822.firebaseapp.com',
    storageBucket: 'gen-lang-client-0115699822.firebasestorage.app',
    measurementId: 'G-7C8NL88H2L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9DQB_K3He2Pp0sktg-i9U9yj3Nd-bMbg',
    appId: '1:49185547481:ios:96aa59baf385ef68f60ac8',
    messagingSenderId: '49185547481',
    projectId: 'gen-lang-client-0115699822',
    storageBucket: 'gen-lang-client-0115699822.firebasestorage.app',
    androidClientId: '49185547481-4v3nbjtam6q8mlrvk9ftfuom22oejfen.apps.googleusercontent.com',
    iosBundleId: 'com.parzello.centrepoint',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9DQB_K3He2Pp0sktg-i9U9yj3Nd-bMbg',
    appId: '1:49185547481:ios:96aa59baf385ef68f60ac8',
    messagingSenderId: '49185547481',
    projectId: 'gen-lang-client-0115699822',
    storageBucket: 'gen-lang-client-0115699822.firebasestorage.app',
    androidClientId: '49185547481-4v3nbjtam6q8mlrvk9ftfuom22oejfen.apps.googleusercontent.com',
    iosBundleId: 'com.parzello.centrepoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy4UXRyOiR9fg90AoUKeIHDEFHSEGLADw',
    appId: '1:49185547481:web:a602dc14f6265804f60ac8',
    messagingSenderId: '49185547481',
    projectId: 'gen-lang-client-0115699822',
    authDomain: 'gen-lang-client-0115699822.firebaseapp.com',
    storageBucket: 'gen-lang-client-0115699822.firebasestorage.app',
    measurementId: 'G-FV6D5B3BW2',
  );
}
